gan_weights:
  desc: GAN weights path
  value: weights/bigbigan.pth
backbone_weights:
  desc: backbone weights path if want to load
  value: null
direction:
  desc: latent direction path
  value: weights/direction.pth
train_embeddings:
  desc: dataset images embeddings path for training
  value: embeddings/cub_train.pth
valid_embeddings:
  desc: dataset images embeddings path for validation
  value: embeddings/cub_valid.pth
test_datasets:
  desc: paths to datasets with ground truth masks to test the model on
  value:
    - data/CUB
    - data/flowers
    - data/DUTS
    - data/ECSSD
    - data/OMRON

n_classes:
  desc: number of the segmentation classes
  value: 2
z_noise:
  desc: amplitude of z noise
  value: 0.1
z_shift:
  desc: norm of the shift along the latent direction
  value: 5.0
fbeta_beta:
  desc: beta value for the F_beta metric
  value: 0.55
backbone_lr:
  desc: backbone learning rate
  value: 0.001
mask_generator_lr:
  desc: mask generator learning rate
  value: 0.0001

train:
  desc: whether to train the model
  value: true
epochs:
  desc: number of epochs to train the model
  value: 1
gan_resolution:
  desc: width and height of generated square images by GAN
  value: 128
model_batch_size:
  desc: the size of minibatches for the segmentation model
  value: 64
gan_batch_size:
  desc: the size of minibatches for GAN generator
  value: 128
model_device:
  desc: CUDA device to use for the model training
  value: 0
gan_device:
  desc: CUDA device to use for generating images with the GAN
  value: 1
train_samples:
  desc: number of samples to use on each epoch for training the model
  value: 100000
valid_samples:
  desc: number of samples to validate trained model on
  value: 10000
seed:
  desc: random seed
  value: null
