model_batch_size:
  desc: the size of minibatches for the segmentation model
  value: 64
gan_batch_size:
  desc: the size of minibatches for GAN generator
  value: 64
connected_components:
  desc: whether to apply connected components filter or not
  value: true
direction:
  desc: latent direction weights path
  value: weights/direction.pth
embeddings:
  desc: dataset images embeddings path
  value: embeddings/flowers.pth
devices:
  desc: CUDA devices to use
  value:
    - 0
    - 1
test_datasets:
  desc: paths to datasets with ground truth masks to test the model on
  value:
    - data/flowers
z_shift:
  desc: norm of the shift along the latent direction
  value: 5.0
mask_size_bound:
  desc: upper bound of the mask size when rejecting a sample
  value: 0.5
mask_size_filter:
  desc: whether to apply mask size filter to generated samples or not
  value: true
maxes_filter:
  desc: whether to apply maxes filter to generated samples or not
  value: true
learning_rate:
  desc: learning rate
  value: 0.001
rate_decay:
  desc: learning rate decay
  value: 0.2
seed:
  desc: random seed (not fixed by default)
  value: null
steps_per_rate_decay:
  desc: steps per learning rate decay
  value: 8000
synthezing:
  desc: null
  value: lighting
valid_samples:
  desc: number of samples to validate trained model on
  value: 64
train_samples:
  desc: number of samples to use on each epoch for training the model
  value: 640
weights:
  desc: GAN weights path
  value: weights/bigbigan.pth
z_noise:
  desc: amplitude of z noise
  value: 0.0
epochs:
  desc: number of epochs to train the model
  value: 10
debug:
  desc: set to number of batches if want a debugging run
  value: false
gan_max_retries:
  desc: maximum value of retries for GAN to sample an image
  value: 100
components_area_bound:
  desc: connected component area lower bound with respect to the maximum component area in the mask
  value: 0.2
fbeta_beta:
  desc: beta value for the F_beta metric
  value: 0.3
