weights:
  desc: GAN weights path
  value: weights/bigbigan.pth
direction:
  desc: latent direction weights path
  value: weights/direction.pth
embeddings:
  desc: dataset images embeddings path
  value: embeddings/imagenet.pth
test_datasets:
  desc: paths to datasets with ground truth masks to test the model on
  value:
    - data/CUB
    - data/flowers
    - data/DUTS
    - data/ECSSD

n_classes:
  desc: number of the segmentation classes
  value: 2
mask_generator:
  desc: type of mask generator for training [scalar/affine/beta]
  value: affine
sigma:
  desc: standard deviation in the shifted color distribution for the mask generator
  value: 1.0
train_mask:
  desc: whether to train fixed mask parameters or not
  value: true
z_noise:
  desc: amplitude of z noise
  value: 0.1
z_shift:
  desc: norm of the shift along the latent direction
  value: 5.0
fbeta_beta:
  desc: beta value for the F_beta metric
  value: 0.55
backbone_lr:
  desc: backbone learning rate
  value: 0.001
mask_generator_lr:
  desc: mask generator learning rate
  value: 0.0001
classes_priors:
  desc: prior probabilities of the segmentation classes
  value:
    - 0.6
    - 0.4
epsilon:
  desc: clamp epsilon for colors beta distribution
  value: 0.01

epochs:
  desc: number of epochs to train the model
  value: 100
gan_resolution:
  desc: width and height of generated square images by GAN
  value: 128
model_batch_size:
  desc: the size of minibatches for the segmentation model
  value: 64
gan_batch_size:
  desc: the size of minibatches for GAN generator
  value: 128
model_device:
  desc: CUDA device to use for the model training
  value: 0
gan_device:
  desc: CUDA device to use for generating images with the GAN
  value: 1
train_samples:
  desc: number of samples to use on each epoch for training the model
  value: 10000
valid_samples:
  desc: number of samples to validate trained model on
  value: 1000
seed:
  desc: random seed
  value: null
