model_batch_size:
  desc: the size of minibatches for the segmentation model
  value: 64
gan_batch_size:
  desc: the size of minibatches for GAN generator
  value: 64
connected_components:
  desc: whether to apply connected components filter or not
  value: true
direction:
  desc: latent direction weights path
  value: weights/direction.pth
embeddings:
  desc: dataset images embeddings path
  value: embeddings/flowers.npy
devices:
  desc: CUDA devices to use
  value:
    - 0
    - 1
datasets:
  desc: paths to datasets with ground truth masks to test the model on
  value:
    - data/flowers
latent_shift_r:
  desc: norm of the shift along the latent direction
  value: 5.0
mask_size_up:
  desc: null
  value: 0.5
maxes_filter:
  desc: null
  value: true
learning_rate:
  desc: learning rate
  value: 0.001
rate_decay:
  desc: learning rate decay
  value: 0.2
seed:
  desc: random seed (not fixed by default)
  value: null
steps_per_rate_decay:
  desc: steps per learning rate decay
  value: 8000
synthezing:
  desc: null
  value: lighting
valid_samples_n:
  desc: number of samples to validate trained model on
  value: 64
train_samples_n:
  desc: number of samples to use on each epoch for training the model
  value: 640
weights:
  desc: GAN weights path
  value: weights/bigbigan.pth
z_noise:
  desc: amplitude of z noise
  value: 0.0
epochs_n:
  desc: number of epochs to train the model
  value: 10
