gan_weights:
  desc: GAN weights path
  value: weights/bigbigan.pth
backbone_weights:
  desc: backbone weights path if want to load
  value: null
directions:
  desc: latent directions path
  value: weights/trained_direction_1.pth
embeddings:
  desc: dataset images embeddings path for training
  value: embeddings/cub.pth
test_datasets:
  desc: paths to datasets with ground truth masks to test the model on
  value:
    - data/CUB
    - data/flowers
    - data/ECSSD
    - data/DUTS
    - data/OMRON

n_classes:
  desc: number of the segmentation classes
  value: 2
z_noise:
  desc: amplitude of z noise
  value: 0.1
z_shift:
  desc: norm of the shift along the latent direction
  value: 5.0
fbeta_beta:
  desc: beta value for the F_beta metric
  value: 0.55
learning_rate:
  desc: model learning rate
  value: 0.001
lr_decay:
  desc: factor which learning rates are multiplied by after every epoch
  value: 0.95

train_model:
  desc: whether to train the model or not
  value: false
epochs:
  desc: number of epochs to train the model
  value: 50
gan_resolution:
  desc: width and height of generated square images by GAN
  value: 432
model_batch_size:
  desc: the size of minibatches for the segmentation model
  value: 64
gan_batch_size:
  desc: the size of minibatches for GAN generator
  value: 128
model_device:
  desc: CUDA device to use for the model training
  value: 0
gan_device:
  desc: CUDA device to use for generating images with the GAN
  value: 1
train_samples:
  desc: number of samples to use on each epoch for training the model
  value: 100000
seed:
  desc: random seed
  value: null
